# Generational models (size offspring = popsize)

In [1]:
import numpy as np

In [2]:
def Models_evaluation(Models: list):
    Mod_eval = {model: {'results':[], 'times':[]} for model in Models}
    best_mean = np.inf
    best_model = ''
    for model in Models:
        results = np.load(model + '.npy')
        # Best
        eval_res = results[0]
        time_res = results[1]
        best_results = eval_res.min(0)
        best_times = time_res.min(0)
        Mod_eval[model]['results'].append(np.append(best_results, best_results.mean()))
        Mod_eval[model]['times'].append(np.append(best_times, best_times.mean()))
        # Worst
        worst_results = eval_res.max(0)
        worst_times = time_res.max(0)
        Mod_eval[model]['results'].append(np.append(worst_results, worst_results.mean()))
        Mod_eval[model]['times'].append(np.append(worst_times, worst_times.mean()))
        # Mean
        mean_results = eval_res.mean(0)
        mean_times = time_res.mean(0)
        Mod_eval[model]['results'].append(np.append(mean_results, mean_results.mean()))
        Mod_eval[model]['times'].append(np.append(mean_times, mean_times.mean()))
        if mean_results.mean() <= best_mean:
            best_model = model
        # Median
        median_results = np.median(eval_res, 0)
        median_times = np.median(time_res, 0)
        Mod_eval[model]['results'].append(np.append(median_results, median_results.mean()))
        Mod_eval[model]['times'].append(np.append(median_times, median_times.mean()))
        # Standard deviation
        std_results = np.std(eval_res, 0)
        std_times = np.std(time_res, 0)
        Mod_eval[model]['results'].append(np.append(std_results, std_results.mean()))
        Mod_eval[model]['times'].append(np.append(std_times, std_times.mean()))
        # Matrix transpose
        Mod_eval[model]['results'] = np.array(Mod_eval[model]['results']).T
        Mod_eval[model]['times'] = np.array(Mod_eval[model]['times']).T
    return Mod_eval, best_model

In [3]:
Generational_models = ['EA1_G_10', 'EA2_G_10', 'EA3_G_10']

In [4]:
Mod_eval_G, best_model_G = Models_evaluation(Generational_models)
print(best_model_G)

EA3_G_10


In [5]:
print(Mod_eval_G[best_model_G]['results'])

[[4.22935094e+09 4.62150825e+10 1.99338652e+10 1.95152221e+10
  1.12064381e+10]
 [4.66263372e+03 2.70073750e+04 1.60995305e+04 1.53810179e+04
  5.74891261e+03]
 [3.49919349e+01 3.14146678e+02 1.39895073e+02 1.40977200e+02
  5.99933847e+01]
 [9.40053013e+00 3.41687243e+01 1.95626262e+01 1.87608837e+01
  6.33559300e+00]
 [2.00002343e+00 3.14752393e+00 2.68289748e+00 2.72293662e+00
  3.11929011e-01]
 [4.10481417e+01 2.05514036e+02 9.42924472e+01 8.59219304e+01
  3.81820641e+01]
 [7.50725340e+00 3.43671326e+01 2.37605791e+01 2.57746566e+01
  7.57346692e+00]
 [5.54645381e+01 6.61158755e+02 3.07227870e+02 2.52202814e+02
  1.70545429e+02]
 [1.44895437e+02 1.19237336e+03 5.64903190e+02 5.91226686e+02
  2.88352997e+02]
 [1.54113966e+06 7.45548349e+07 2.54893697e+07 1.41384736e+07
  2.24752028e+07]
 [4.23089704e+08 4.62896668e+09 1.99593718e+09 1.95293771e+09
  1.12289196e+09]]


In [6]:
print(Mod_eval_G[best_model_G]['times'])

[[0.1882     0.3252     0.24119    0.23975    0.03470119]
 [0.2227     0.3279     0.27398    0.25825    0.03684149]
 [0.207      0.3212     0.253215   0.24675    0.03122913]
 [0.203      0.3126     0.25443    0.24945    0.03481381]
 [0.2307     0.3571     0.26839    0.2565     0.03336506]
 [0.2646     0.372      0.308865   0.3092     0.03393201]
 [0.2226     0.4135     0.284365   0.2666     0.05524218]
 [0.2328     0.3411     0.28676    0.2852     0.03798898]
 [0.2393     0.3717     0.292755   0.27265    0.04538352]
 [0.2119     0.3426     0.262065   0.2554     0.03749051]
 [0.22228    0.34849    0.2726015  0.263975   0.03809879]]


In [7]:
Generational_models = ['EA1_G_30', 'EA2_G_30', 'EA3_G_30']
Mod_eval_G, best_model_G = Models_evaluation(Generational_models)
print(best_model_G)

EA3_G_30


In [8]:
print(Mod_eval_G[best_model_G]['results'])

[[1.36456604e+10 9.94358924e+10 4.60630626e+10 4.11368433e+10
  2.00415097e+10]
 [5.17756158e+04 9.57879789e+04 7.24247977e+04 7.08858508e+04
  1.14118581e+04]
 [2.81442841e+02 1.39636322e+03 5.54300999e+02 5.24222064e+02
  2.24409909e+02]
 [4.34450092e+01 1.07330432e+02 7.12195201e+01 6.98655323e+01
  1.68152582e+01]
 [9.68849557e+00 1.18674632e+01 1.05393919e+01 1.05837349e+01
  4.55147952e-01]
 [2.27136515e+02 7.86445490e+02 4.88304169e+02 5.07375327e+02
  1.27894953e+02]
 [4.60658668e+01 8.70111510e+01 7.05813711e+01 7.31332542e+01
  1.21733859e+01]
 [7.18104855e+02 2.00175380e+03 1.18039058e+03 1.14693281e+03
  3.40018535e+02]
 [1.39526692e+03 3.18002612e+03 2.08895861e+03 2.00249456e+03
  4.97493654e+02]
 [6.68793838e+06 1.29407612e+08 4.05949422e+07 3.20493936e+07
  2.87936741e+07]
 [1.36524029e+09 9.95654034e+09 4.61037345e+09 4.11689679e+09
  2.00703160e+09]]


In [9]:
print(Mod_eval_G[best_model_G]['times'])

[[0.7201     1.0071     0.845835   0.8184     0.08630778]
 [0.7843     1.2623     0.93769    0.92225    0.10826582]
 [0.7408     1.3291     0.89173    0.89275    0.12185241]
 [0.7573     1.0697     0.86098    0.8372     0.07700106]
 [0.7911     1.0575     0.903045   0.8833     0.07931416]
 [0.8857     1.2981     1.08564    1.06425    0.12126368]
 [0.8212     1.1433     0.93968    0.92985    0.08473706]
 [0.813      1.3665     0.995675   0.96385    0.12559614]
 [0.8402     2.2565     1.071355   0.9966     0.29476542]
 [0.7564     1.5        0.92937    0.914      0.15911591]
 [0.79101    1.32901    0.9461     0.922245   0.12582194]]


# Steady-State models (size offspring < popsize)

In [10]:
Steady_state_models = ['EA1_SS_10', 'EA2_SS_10', 'EA3_SS_10']

In [11]:
Mod_eval_SS, best_model_SS = Models_evaluation(Steady_state_models)
print(best_model_SS)

EA3_SS_10


In [12]:
print(Mod_eval_SS[best_model_SS]['results'])

[[2.42497378e+09 3.44198375e+10 1.28137851e+10 1.06833687e+10
  9.32861663e+09]
 [6.80630294e+03 2.56117084e+04 1.71181054e+04 1.76018334e+04
  4.53644318e+03]
 [3.26750720e+01 1.62817285e+02 8.86222625e+01 8.67776796e+01
  3.54108684e+01]
 [1.13840062e+01 3.47969751e+01 1.88856672e+01 1.95844517e+01
  5.78555572e+00]
 [1.51100334e+00 3.40457298e+00 2.43181921e+00 2.38290299e+00
  5.56971598e-01]
 [6.23631525e+01 1.42777970e+02 9.11622905e+01 8.93305989e+01
  1.84589522e+01]
 [1.11353271e+01 4.11673751e+01 2.18325734e+01 2.30224461e+01
  7.52333367e+00]
 [5.57021224e+01 3.99494322e+02 2.59674019e+02 2.71777989e+02
  9.44115429e+01]
 [3.74911833e+01 8.50291133e+02 3.85887603e+02 3.20772502e+02
  2.63552107e+02]
 [1.59165885e+06 2.39394720e+07 7.11504282e+06 4.85865337e+06
  5.71005381e+06]
 [2.42657245e+08 3.44438042e+09 1.28209181e+09 1.06882458e+09
  9.33433164e+08]]


In [13]:
print(Mod_eval_SS[best_model_SS]['times'])

[[0.1504     0.2507     0.183215   0.17665    0.02629405]
 [0.1826     0.327      0.21208    0.2045     0.03384222]
 [0.1668     0.2947     0.19126    0.17735    0.03402426]
 [0.1579     0.2407     0.179895   0.17745    0.01864973]
 [0.1758     0.2446     0.195565   0.19005    0.01790964]
 [0.2239     0.3445     0.25522    0.2443     0.02812946]
 [0.1837     0.2944     0.210345   0.20025    0.02553753]
 [0.1867     0.2932     0.215205   0.20645    0.02399784]
 [0.2029     0.3467     0.226885   0.21525    0.03156652]
 [0.1676     0.2721     0.201125   0.1992     0.0243031 ]
 [0.17983    0.29086    0.2070795  0.199145   0.02642544]]


In [14]:
Steady_state_models = ['EA1_SS_30', 'EA2_SS_30', 'EA3_SS_30']

In [15]:
Mod_eval_SS, best_model_SS = Models_evaluation(Steady_state_models)
print(best_model_SS)

EA3_SS_30


In [16]:
print(Mod_eval_SS[best_model_SS]['results'])

[[3.04875845e+10 1.12249039e+11 6.60187335e+10 6.56426004e+10
  1.90588986e+10]
 [5.64075431e+04 9.47777958e+04 7.77484119e+04 7.81789732e+04
  9.81578791e+03]
 [3.86595410e+02 2.30147247e+03 7.48142222e+02 6.63350887e+02
  4.17999208e+02]
 [4.82294726e+01 1.21147711e+02 8.18230518e+01 8.16193392e+01
  1.99941130e+01]
 [9.11013021e+00 1.19904981e+01 1.07553087e+01 1.06824223e+01
  8.34863523e-01]
 [4.41091724e+02 7.99769208e+02 5.79466464e+02 5.48384263e+02
  9.92217160e+01]
 [4.72861113e+01 1.03260296e+02 6.75998165e+01 6.75274928e+01
  1.38791699e+01]
 [8.52377375e+02 2.66021253e+03 1.70099848e+03 1.62387464e+03
  5.49931225e+02]
 [7.82822812e+02 2.56548809e+03 1.96545504e+03 2.07565798e+03
  4.77096067e+02]
 [1.50516607e+07 2.33720474e+08 6.56907059e+07 5.67521227e+07
  4.92464505e+07]
 [3.05026952e+09 1.12482863e+10 6.60845071e+09 6.56994358e+09
  1.91081565e+09]]


In [17]:
print(Mod_eval_SS[best_model_SS]['times'])

[[0.5779     1.3135     0.69769    0.67085    0.14705016]
 [0.6762     1.375      0.795655   0.75805    0.14349722]
 [0.6116     1.1085     0.740615   0.70935    0.10394731]
 [0.6363     0.916      0.727515   0.7025     0.08263028]
 [0.6534     0.9088     0.73361    0.72175    0.06826235]
 [0.7899     1.7739     0.942535   0.8776     0.20895942]
 [0.6852     1.3424     0.83017    0.7767     0.14323584]
 [0.7236     1.1843     0.824755   0.7904     0.10694467]
 [0.7432     1.6777     0.928845   0.8308     0.22630185]
 [0.6655     1.1543     0.776215   0.72335    0.13021963]
 [0.67628    1.27544    0.7997605  0.756135   0.13610487]]
